ARG CUDA_VERSION=9.0
FROM mitmul/pynvvl:cuda-${CUDA_VERSION}

RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    python3-tk \
    gawk

RUN pip3 install \
    cython \
    numpy \
    matplotlib

ARG CUPY_PACKAGE_NAME
RUN pip3 install ${CUPY_PACKAGE_NAME}
